---

layout: page
lang: "de"
journal: "LIBREAS. Library Ideas"
issue: "39"
year: "2021"
contributor: 
- Sara Juen
title: "Feminismus, Algorithmen, Gender-Data-Gap und was das alles mit Bibliotheks- und Informationswissenschaft zu tun hat"
pdf: "https://doi.org/10.18452/23448"
doi: "10.18452/23448"
date: 2021-09-30
comments: false
sharing: true
footer: true

---
