---

layout: page
lang: "de"
journal: "LIBREAS. Library Ideas"
issue: "39"
year: "2021"
contributor: 
- Victoria Geske
- Yannick Paulsen
- Heidrun Wiesenmüller
- Daniel Brenn
- Beat Mattmann
title: "Communitybuilding über Discord – der DACH-Bibliothekswesen-Server"
pdf: "main.pdf"
date: 2021-10-03
comments: false
sharing: true
footer: true

---