---

layout: page
lang: "de"
journal: "LIBREAS. Library Ideas"
issue: "39"
year: "2021"
contributor: 
- Christian Winkler
title: "Digitalisierung am Deutschen Museum – alles andere als retro"
pdf: "main.pdf"
date: 2021-09-30
comments: false
sharing: true
footer: true

---