---

layout: page
lang: "de"
journal: "LIBREAS. Library Ideas"
issue: "39"
year: "2021"
contributor: 
- Andreas Urech
- Marisa Eberle
- Roger Burkhard
title: "Entwicklung von nützlichen Einsatzszenarien für Soziale Roboter in den Bibliotheken der FHNW"
pdf: "master.pdf"
date: 2021-09-15
comments: false
sharing: true
footer: true

---
